# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophertype < Formula
  desc "Terminal-based typing practice tool with real-time WPM and accuracy tracking"
  homepage "https://github.com/treygilliland/zootype"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.1/gophertype_0.0.1_darwin_amd64.tar.gz"
    sha256 "1482adc93400b1f02bdc67bf4145a96eda767472d802cfb73353e982d201dd1d"

    def install
      bin.install "gophertype"
    end
  end
  if Hardware::CPU.arm?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.1/gophertype_0.0.1_darwin_arm64.tar.gz"
    sha256 "c7b7a45662793c8be49fdb73833205c2f0608882ae7dfc10f68630a0bb444917"

    def install
      bin.install "gophertype"
    end
  end

  test do
    system "#{bin}/gophertype", "--version"
  end
end
