# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophertype < Formula
  desc "Terminal-based typing practice tool with real-time WPM and accuracy tracking"
  homepage "https://github.com/treygilliland/zootype"
  version "0.0.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.4/gophertype_0.0.4_darwin_amd64.tar.gz"
    sha256 "a82489a10125e4bcb80d70c63f361880082796fb8119b115f094f07c35775a2f"

    def install
      bin.install "gophertype"
    end
  end
  if Hardware::CPU.arm?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.4/gophertype_0.0.4_darwin_arm64.tar.gz"
    sha256 "ae7badcb373e24ddc94b1007ea505a0b0d262f9b62adee32b4f39ab7f39b3c4c"

    def install
      bin.install "gophertype"
    end
  end

  test do
    system "#{bin}/gophertype", "--version"
  end
end
