# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophertype < Formula
  desc "Terminal-based typing practice tool with real-time WPM and accuracy tracking"
  homepage "https://github.com/treygilliland/zootype"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.1/gophertype_0.0.1_darwin_amd64.tar.gz"
    sha256 "bed385784e8546872f6f3b4f02a53c58a53ac454f104614276eef7f17aee6cc7"

    def install
      bin.install "gophertype"
    end
  end
  if Hardware::CPU.arm?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.1/gophertype_0.0.1_darwin_arm64.tar.gz"
    sha256 "d1a4fad8b1e0feff433e2eac4c636d8e6eb8269e2db2be5919cc10c54fe0b717"

    def install
      bin.install "gophertype"
    end
  end

  test do
    system "#{bin}/gophertype", "--version"
  end
end
