# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zootype < Formula
  desc "Terminal-based typing practice tool with real-time WPM and accuracy tracking"
  homepage "https://github.com/treygilliland/zootype"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.1/zootype_0.0.1_darwin_amd64.tar.gz"
    sha256 "ffc5e8e48bcbe3d67c37870680e3041b712cce307dd0c9e019287d5a376b3c2d"

    def install
      bin.install "gophertype"
    end
  end
  if Hardware::CPU.arm?
    url "https://pub-6085c325f09e4e99bb69108db6dd11a5.r2.dev/releases/0.0.1/zootype_0.0.1_darwin_arm64.tar.gz"
    sha256 "fb47b81efb5a50b9aed508bfc87167cfb5ff164386b96338c5423290a65f6ebe"

    def install
      bin.install "gophertype"
    end
  end

  test do
    system "#{bin}/gophertype", "--version"
  end
end
